spring.application.name=prueba-tecnica-macronnect

# msql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:bd_pm}?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true

spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:admin}

# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# jwt
jwt.secret=d2lmZXRvcHByZXNlbnR0cmFpbG1lYXN1cmVyb3VnaHdvcmtmaXJlcGxhY2VyZWNlaXZlc2FpZGZhc3RlcmJsYQ==
jwt.expiration=3600000